export const data = {
  pagination: {
    page: 1,
    pages: 172,
    per_page: 5,
    items: 860,
    urls: {
      last: "https://api.discogs.com/database/search?release_title=nevermind&artist=nirvana&per_page=5&page=172&token=ibRYwKsepPPXfwybJDQiPWwzQWTJfLwJwqoFHlrM",
      next: "https://api.discogs.com/database/search?release_title=nevermind&artist=nirvana&per_page=5&page=2&token=ibRYwKsepPPXfwybJDQiPWwzQWTJfLwJwqoFHlrM",
    },
  },
  results: [
    {
      country: "Europe",
      genre: ["Rock"],
      format: ["Vinyl", "LP", "Album", "Unofficial Release"],
      style: ["Grunge"],
      id: 464021,
      label: ["Geffen Records Company; Sub-Pop"],
      type: "master",
      barcode: ["0-720642-442517", "LC-07266", "424 425-1   "],
      user_data: { in_wantlist: false, in_collection: false },
      master_id: 464021,
      master_url: "https://api.discogs.com/masters/464021",
      uri: "/Nirvana-Nevermind/master/464021",
      catno: "424 425-1",
      title: "Nirvana - Nevermind",
      thumb:
        "https://i.discogs.com/956k7Z_n3l-Fkp7Pvdm7wt8rCjEsYaCslIk6pzxWSHg/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2ODY4/MjktMTM0MDUzMTI1/NC0zNTQzLmpwZWc.jpeg",
      cover_image:
        "https://i.discogs.com/x3_an7MFpKhKDsCvnRJwsQDDJvXAtWrb96k3XMPnRUE/rs:fit/g:sm/q:90/h:317/w:320/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2ODY4/MjktMTM0MDUzMTI1/NC0zNTQzLmpwZWc.jpeg",
      resource_url: "https://api.discogs.com/masters/464021",
      community: { want: 0, have: 0 },
    },
    {
      country: "US",
      year: "2004",
      format: ["DVD", "NTSC", "DVD-Video"],
      label: [
        "Eagle Vision",
        "Eagle Vision",
        "Eagle Vision",
        "WWW.DISCUSA.COM",
        "Classic Albums",
      ],
      type: "master",
      genre: ["Rock", "Non-Music"],
      style: ["Interview", "Grunge"],
      id: 204840,
      barcode: [
        "8 01213 00699 1",
        "IFPI L795",
        "IFPI 2D4V",
        "WWW.DISCUSA.COM EV 30069-9 05 2/18/05 DVD",
      ],
      user_data: { in_wantlist: false, in_collection: false },
      master_id: 204840,
      master_url: "https://api.discogs.com/masters/204840",
      uri: "/master/204840-Nirvana-Nevermind",
      catno: "EV 30069-9",
      title: "Nirvana - Nevermind",
      thumb:
        "https://i.discogs.com/ozN8nOpMeVLlGOJjbnQGFij3ErsRmZfItTz9Y8SH_7c/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyNzA3/NzktMTMyMzUyMDEy/MS5qcGVn.jpeg",
      cover_image:
        "https://i.discogs.com/bD8pyKmRJATlwkSp9yBexP6KMRzIW4mgUatP1sUi620/rs:fit/g:sm/q:90/h:842/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyNzA3/NzktMTMyMzUyMDEy/MS5qcGVn.jpeg",
      resource_url: "https://api.discogs.com/masters/204840",
      community: { want: 385, have: 1328 },
    },
    {
      country: "US",
      year: "1991",
      format: ["CD", "Album", "Mispress"],
      label: [
        "DGC",
        "Sub Pop",
        "The David Geffen Company",
        "The David Geffen Company",
        "Uni Distribution Corp.",
        "Uni Distribution Corp.",
        "Virgin Songs, Inc.",
        "The End Of Music",
        "Virgin Songs, Inc.",
        "The End Of Music",
        "Digital Audio Disc Corp.",
        "Sound City Studios",
        "Scream Studios",
        "Masterdisk",
        "DADC",
      ],
      type: "master",
      genre: ["Rock"],
      style: ["Grunge"],
      id: 13814,
      barcode: [
        "7 2064-24425-2 4",
        "720642442524",
        "AAD",
        "BMI",
        "DIDX 011927",
        "DIDX-011927 3",
        "[DADC 'D' logo]",
        "DIDX-011927 6",
        "Made In USA - Digital Audio Disc Corp.",
        "DIDX-011927 5",
        "[DADC 'D' logo]",
        "DIDX-011927 5",
        "none",
        "DIDX-011927 7",
        "none",
        "DIDX-011927 5",
        "Made In USA - Digital Audio Disc Corp.",
        "DIDX-011927 1",
        "[DADC 'D' logo]",
        "DIDX\u2013011927 6",
        "none",
      ],
      user_data: { in_wantlist: false, in_collection: false },
      master_id: 13814,
      master_url: "https://api.discogs.com/masters/13814",
      uri: "/master/13814-Nirvana-Nevermind",
      catno: "DGCD-24425",
      title: "Nirvana - Nevermind",
      thumb:
        "https://i.discogs.com/s58EpifqEvUTu0YOonHgIr_pxSmyfPz4JlvUuuRpvmo/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2NzA4/NC0xMjYzMDk1NTUz/LmpwZWc.jpeg",
      cover_image:
        "https://i.discogs.com/XoAXkLe03Vk0Kt-oQqw7V9uW5nBzQdNvZd0zar5mOiQ/rs:fit/g:sm/q:90/h:592/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2NzA4/NC0xMjYzMDk1NTUz/LmpwZWc.jpeg",
      resource_url: "https://api.discogs.com/masters/13814",
      community: { want: 438391, have: 306735 },
    },
    {
      country: "Europe",
      year: "2002",
      format: ["CD", "Unofficial Release", "Compilation"],
      label: ["Not On Label (Nirvana)"],
      type: "master",
      genre: ["Rock"],
      style: ["Grunge"],
      id: 391894,
      barcode: ["NNS CD 24425", "ADD"],
      user_data: { in_wantlist: false, in_collection: false },
      master_id: 391894,
      master_url: "https://api.discogs.com/masters/391894",
      uri: "/master/391894-Nirvana-Nevermind-Sessions",
      catno: "NNSCD 24425",
      title: "Nirvana - Nevermind Sessions",
      thumb:
        "https://i.discogs.com/CnWZbxAR0cU6oP8avfz_CnPzhtjZWiyGguymV0uRLF0/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE5OTk4/NTAtMTYyOTQ5OTYz/Mi03Nzk2LmpwZWc.jpeg",
      cover_image:
        "https://i.discogs.com/2qHzL-n_mB-cecMIvajVWIlCImdKTbAYVFXZG5rmT5w/rs:fit/g:sm/q:90/h:599/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE5OTk4/NTAtMTYyOTQ5OTYz/Mi03Nzk2LmpwZWc.jpeg",
      resource_url: "https://api.discogs.com/masters/391894",
      community: { want: 89, have: 183 },
    },
    {
      country: "US",
      year: "1992",
      format: ["CD", "Promo"],
      label: [
        "DGC",
        "Sub Pop",
        "Uni Distribution Corp.",
        "Uni Distribution Corp.",
        "The David Geffen Company",
        "The David Geffen Company",
        "Specialty Records Corporation",
      ],
      type: "master",
      genre: ["Rock", "Non-Music"],
      style: ["Interview", "Grunge", "Alternative Rock"],
      id: 958122,
      barcode: ["38 PRO CD 4382-2 SRC*01 M1S2"],
      user_data: { in_wantlist: false, in_collection: false },
      master_id: 958122,
      master_url: "https://api.discogs.com/masters/958122",
      uri: "/master/958122-Nirvana-Nevermind-Its-An-Interview",
      catno: "PRO-CD-4382",
      title: "Nirvana - Nevermind, It's An Interview",
      thumb:
        "https://i.discogs.com/bvxdQGISew8nCi_QK2e4XHge2zSOiQzUBVKTFKEmR8Q/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIyNTUz/MTItMTU0NzM3MjQ2/Mi0yMzA2LmpwZWc.jpeg",
      cover_image:
        "https://i.discogs.com/RIdH1HTR8QyCt9b5neaiOUnnvfzMFaIW3PCU8-dnJcA/rs:fit/g:sm/q:90/h:547/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIyNTUz/MTItMTU0NzM3MjQ2/Mi0yMzA2LmpwZWc.jpeg",
      resource_url: "https://api.discogs.com/masters/958122",
      community: { want: 346, have: 355 },
    },
  ],
};

export const albumData = {
  id: 464021,
  main_release: 3686829,
  most_recent_release: null,
  resource_url: "https://api.discogs.com/masters/464021",
  uri: "https://www.discogs.com/master/464021-Nirvana-Nevermind",
  versions_url: "https://api.discogs.com/masters/464021/versions",
  main_release_url: "https://api.discogs.com/releases/3686829",
  most_recent_release_url: "",
  num_for_sale: 0,
  lowest_price: null,
  images: [
    {
      type: "primary",
      uri: "",
      resource_url: "",
      uri150: "",
      width: 320,
      height: 317,
    },
    {
      type: "secondary",
      uri: "",
      resource_url: "",
      uri150: "",
      width: 600,
      height: 600,
    },
  ],
  genres: ["Rock"],
  styles: ["Grunge"],
  year: 0,
  tracklist: [
    {
      position: "A1",
      type_: "track",
      title: "Smells Like Teen Spirit (Radio Version)",
      duration: "",
    },
    { position: "A2", type_: "track", title: "In Bloom", duration: "" },
    {
      position: "A3",
      type_: "track",
      title: "Come As You Are (Radio Version)",
      duration: "",
    },
    { position: "A4", type_: "track", title: "Breed", duration: "" },
    { position: "A5", type_: "track", title: "Lithium", duration: "" },
    { position: "A6", type_: "track", title: "Polly", duration: "" },
    { position: "A7", type_: "track", title: "Untitled", duration: "" },
    {
      position: "B1",
      type_: "track",
      title: "Territorial Pissings",
      duration: "",
    },
    { position: "B2", type_: "track", title: "Drain You", duration: "" },
    { position: "B3", type_: "track", title: "Lounge Act", duration: "" },
    { position: "B4", type_: "track", title: "On A Plain", duration: "" },
    { position: "B5", type_: "track", title: "Stay Away", duration: "" },
    {
      position: "B6",
      type_: "track",
      title: "Something In The Way",
      duration: "",
    },
  ],
  artists: [
    {
      name: "Nirvana",
      anv: "",
      join: "",
      role: "",
      tracks: "",
      id: 125246,
      resource_url: "https://api.discogs.com/artists/125246",
    },
  ],
  title: "Nevermind",
  data_quality: "Correct",
};
